use_frameworks!

platform :ios, '10.0'

target 'TCAlertController_Example' do
  pod 'TCAlertController', :path => '../'

  target 'TCAlertController_Tests' do
    inherit! :search_paths

    
  end
end
